function phoneticizePinyin(pinyin) {
pinyin = pinyin.replaceAll("uang","oo'ang")
pinyin = pinyin.replaceAll("uan","oo'an")
pinyin = pinyin.replaceAll("uai","oo'ai")
pinyin = pinyin.replaceAll("iu","you")
pinyin = pinyin.replaceAll("un","oo'on")
pinyin = pinyin.replaceAll("ui","oo'ei")
pinyin = pinyin.replaceAll("ua","oo'a")
pinyin = pinyin.replaceAll("uo","oo'oh")
pinyin = pinyin.replaceAll("iong","yong")
pinyin = pinyin.replaceAll("ing","ying")
pinyin = pinyin.replaceAll("iao","yao")
pinyin = pinyin.replaceAll("iang","yang")
pinyin = pinyin.replaceAll("ian","yan")
pinyin = pinyin.replaceAll("ong","oo'eng")
pinyin = pinyin.replaceAll("shi","shh")
pinyin = pinyin.replaceAll("chi","chh")
pinyin = pinyin.replaceAll("ang","ong")
pinyin = pinyin.replaceAll("ai","e")
pinyin = pinyin.replaceAll("ei","e")
pinyin = pinyin.replaceAll("ou","o")
pinyin = pinyin.replaceAll("zi","zz")
pinyin = pinyin.replaceAll("io","yo")
pinyin = pinyin.replaceAll("in","yin")
pinyin = pinyin.replaceAll("ie","ye")
pinyin = pinyin.replaceAll("ia","ya")
pinyin = pinyin.replaceAll("si","sz")
pinyin = pinyin.replaceAll("ri","rr")
pinyin = pinyin.replaceAll("ci","cz")
pinyin = pinyin.replaceAll("zh","ch")
pinyin = pinyin.replaceAll("ao","A-o")
pinyin = pinyin.replaceAll("z","c")
pinyin = pinyin.replaceAll("x","ş")
pinyin = pinyin.replaceAll("u","oo")
pinyin = pinyin.replaceAll("q","chi")
pinyin = pinyin.replaceAll("j","chai")
pinyin = pinyin.replaceAll("i","ee")
pinyin = pinyin.replaceAll("g","k")
pinyin = pinyin.replaceAll("e","u")
pinyin = pinyin.replaceAll("d","t")
pinyin = pinyin.replaceAll("c","ts")
pinyin = pinyin.replaceAll("b","p")
return pinyin
}


